Fix fallback MODX_CORE_PATH in manager/min/index.php
Error: When `manager/config.core.php` doesn't exist, `MODX_CORE_PATH`
in manager/min becomes `%modx base%/manager/core` instead of `%modx
base%/core`